version: "3.8"

services:
  p13:
    container_name: p13
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

  mariadb:
    container_name: p13_mariadb
    image: "mariadb:latest"
    environment:
      MARIADB_DATABASE: mydatabase
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: myuser
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb", "-u", "myuser", "-psecret", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
